#!/bin/bash

#Script para correr un blast

#Nos ubicamos en el directorio raíz. Se baja el biocontenedor con blast. Se abre el menú de ayuda de blast del biocontenedor.

cd ~/
docker pull biocontainers/blast
docker run biocontainers/blast blastp -help

#Se obtiene la proteina prion en formato fasta. Se baja la base de datos de proteinas del NCBI y se descomprime.

wget http://www.uniprot.org/uniprot/P04156.fasta    
curl -O ftp://ftp.ncbi.nih.gov/refseq/D_rerio/mRNA_Prot/zebrafish.1.protein.faa.gz
gunzip zebrafish.1.protein.faa.gz

#Se monta un volúmen llamado "data" en el home, en el cual se abre el contenedor con el blast. En este se corre "makeblastdb para generar los archivos de la base de datos del BLAST. 
docker run -v ~/:/data/ biocontainers/blast makeblastdb -in zebrafish.1.protein.faa -dbtype prot

#Finalmente se corre el blast, buscando la secuencia P04156.fasta en el archivo que se generó de la base de datos del genoma completo de zebrafish, generando un archivo results.txt con el output.
docker run -v ~/:/data/ biocontainers/blast blastp -query P04156.fasta -db zebrafish.1.protein.faa -out results.txt

